### ISSUE TITLE
License for newl-compiler

### ISSUE THREAD

**Issue by christabelneo** [bjwbell/newl-compiler#1]
Hi Bryan,

I've tried contacting you by email as I'm doing work that is very similar to what you have done here with newl, and would really love to get some advice from you. 

Hope to hear back from you soon,
Christabel

**Comment by bjwbell** [comment]
Hi Christa, I've added an MIT LICENSE file. Let me know if you need anything else.

**Comment by christabelneo** [comment]
Hi Bryan,

Thanks for the quick response! Yes actually it'd be great if you could help me with an issue I've been struggling with:

As my language differs from newl in some respects, I'm having some trouble figuring out how to modify the symbol table part of your code. In particular, my grammar has the following productions (in the same style as your ExpList and ExpRest ones)

FormalList :
Type ident FormalRest  {FormalList $1 $2 $3}
|           {FEmpty}
FormalRest :
"," Type ident FormalRest  {FormalRest $2 $3 $4}
|           {PEmpty}


But this means that when it comes to defining argSymbols for the symbol table, the code doesn't work because FormalList doesn't pattern-match with FormalRest.

Thank you so much for your time!

Best wishes,
Christabel

Sent from my iPhone

On 16 Jul 2017, at 18:31, JW Bell <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Christa, I've added an MIT LICENSE file. Let me know if you need anything else.
